### PR TITLE
Added Territory2 object as a picklist value in non-entity object.

### PR DESCRIPTION
**Pull request by rgasan**
Updated Custom Metadata Trigger Management Entry - Added Territory2 object as a picklist value in non-entity object.

### CODE REVIEW

**Review by docbill — APPROVED** [review]
Fortunately a field does not need to be valid in order to appear in this picklist.  So this should not break orgs not using territories.

I will need to do the build manually, and will post when this is complete.

**Comment by rgasan** [comment]
Thanks Bill @docbill

**Comment by docbill** [comment]
@rgasan The following is the difference you need to apply to your redhatcrm branch:

```
diff --git a/sfdx-project.json b/sfdx-project.json
index 86c8c856c..d3f381019 100644
--- a/sfdx-project.json
+++ b/sfdx-project.json
@@ -683,7 +683,7 @@
   "sfdcLoginUrl": "https://login.salesforce.com",
   "sourceApiVersion": "61.0",
   "packageAliases": {
-    "ApexFramework": "04t6e000002VmYqAAK",
+    "ApexFramework": "04t6e0000029VK7AAM",
     "JSON-Mapper": "04t6e0000029NwbAAE",
     "SBQQ": "04t6T000001hKFbQAM",
     "sbaa": "04t4W000002g35xQAA",
```

**Comment by docbill** [comment]
@rgasan The sf package:install command can be used to install the package in your scratch org.  But since you should already have the update in the scratch org, you probably don't need to do that.

**Pull request merged**
